name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: windows-latest
    steps:
      - name: testomatio
        uses: cypress-io/github-action@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 10
          spec: cypress\e2e\**.cy.js          
