name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: windows-latest
    steps:
      - name: pushing-it
        uses: actions/checkout@v2

      - name: Testomatio
        uses: cypress-io/github-action@v4
        with:
          spec: cypress\e2e\**.cy.js          
