name: Cypress tests

on:
  workflow_dispatch:
    inputs:
      grep:
        description: 'tests to grep '
        required: false
        default: ''
      run:
        required: false
      testomatio:
        required: false
      testomatio_url:
        required: false

jobs:
   build:
    runs-on: windows-latest
    steps:
    - run: npm i
    - run: npx cypress run --grep "${{ github.event.inputs.grep }}"
      env: 
        TESTOMATIO: "${{ github.event.inputs.testomatio }}"
        
        
